name: Android Test

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
  pull_request:

jobs:
  android-test:
    runs-on: macos-26-intel
    timeout-minutes: 60

    env:
      APPIUM_HOST: 127.0.0.1
      APPIUM_PORT: 4723
      APPIUM_BASE_PATH: /wd/hub

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install npm dependencies
        run: npm ci

      - name: Install Appium and UiAutomator2 driver
        run: |
          npm install -g appium

      - name: Run Android emulator, start Appium
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: x86_64
          # arch: arm64-v8a
          profile: pixel_7
          target: google_apis
          emulator-boot-timeout: 900
          disable-animations: true
          force-avd-creation: true
          pre-emulator-launch-script: |
            adb kill-server || true
            adb start-server
            adb devices
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-metrics -no-snapshot -wipe-data
          script: |
            adb devices
            adb wait-for-device

            sleep 30

            adb shell getprop sys.boot_completed
            adb shell getprop ro.build.version.release
            adb shell getprop ro.build.version.sdk


            adb shell settings put global window_animation_scale 0
            adb shell settings put global transition_animation_scale 0
            adb shell settings put global animator_duration_scale 0

            nohup appium --address $APPIUM_HOST --port $APPIUM_PORT --base-path $APPIUM_BASE_PATH --log ./appium.log > ./appium.out 2>&1 &

            echo "Waiting for Appium to be ready..."            

            sleep 30

            curl --fail "http://$APPIUM_HOST:$APPIUM_PORT$APPIUM_BASE_PATH/status"

      - name: Create .env file
        run: |
          echo "TEST_USER_1_USERNAME=${{ secrets.TEST_USER_1_USERNAME }}" >> .env
          echo "TEST_USER_1_PASSWORD=${{ secrets.TEST_USER_1_PASSWORD }}" >> .env

      - name: Run Tests
        run: |
          npm run test:demo

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            logs
            ./appium.log
            ./appium.out
          if-no-files-found: ignore
